version: "3.3"

services:
  backend:
    container_name: backend
    build:
      dockerfile: Dockerfile
      context: ./backend
    image: backend
    command: ["npm", "run", "dev"]
    ports:
      - target: 8080
        published: 8080
        protocol: tcp
        mode: host
    volumes:
      - ./backend:/usr/src/app
      - /usr/src/app/node_modules
    # command: ["./utils/wait-for-it.sh", "postgres:5432", "--",  "npm", "start"]
    depends_on:
      - db
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_HOST=${POSTGRES_HOST}
      - POSTGRES_PORT=${POSTGRES_PORT}
      - POSTGRES_DATABASE=${POSTGRES_DATABASE}
      - DATABASE_URL=postgres://TIE:ZAQ!2wsx@postgres:5432/beacon_attendance
      - ADMIN_EMAIL=admin.one@tuni.fi
      - ADMIN_PASSWORD=password
      - TEST_HOST=backend
  db:
    container_name: postgres
    build:
      dockerfile: Dockerfile
      context: ./db
    restart: always
    volumes:
      - pg-data-ble:/var/lib/postgresql/data
    ports:
      - 5432:5432
networks:
  default:
    driver: bridge
volumes:
  pg-data-ble:
    driver: local